version: '3'
services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: poboard
      POSTGRES_PASSWORD: asdfasdf
      POSTGRES_DB: poboard

  git-server:
    build:
      context: ./git-server
    ports:
      - "10122:22"