version: "1.0"
defaults:
  reloadTimeoutMillis: null
  connectTimeoutMillis: null
  readTimeoutMillis: null
  recheckTimeoutMillis: null
  versionAliases: []
  branchAliases: []
  commitishAliases: []
  buildTimestampAliases: []
workspace:
  dir: /tmp/deploymentboard-workspace
environments:
systems:
projects:
credentials:
