version: '3'
services:
  deploymentboard:
    image: cbuschka/deploymentboard:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - "JAVA_TOOL_OPTIONS=-Ddeploymentboard.config=file:/config/test-config.yaml -Ddeploymentboard.masterpassword="
    volumes:
      - "${TOP_DIR}/backend/src/test/resources/test-config.yaml:/config/test-config.yaml:ro"
